cmd/telemeter-server/main.go
pkg/cluster/cluster.go
pkg/http/server/server.go

Makes life just a bit easier for everyone

Use a summary metric instead of a histogram

---

jsonnet/jsonnetfile.lock.json
jsonnet/main.jsonnet
jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
jsonnet/telemeter/client/telemeter-client.libsonnet

jsonnet: address pr 25 nits

---

deploy/telemeter-server.yaml

Template will allow us to override image / image tag

makes telemeter-server.yaml template

---

deploy/telemeter-server.yaml

This reflects also api.ci deployment.
/cc @squat @riuvshin @jmelis

deploy: set replica count to 3

---

deploy/telemeter-server.yaml

deploy: set tollbooth authorize url

---

glide.lock
glide.yaml
vendor/github.com/coreos/go-oidc/.gitignore
vendor/github.com/coreos/go-oidc/.travis.yml
vendor/github.com/coreos/go-oidc/CONTRIBUTING.md
vendor/github.com/coreos/go-oidc/DCO
vendor/github.com/coreos/go-oidc/LICENSE
vendor/github.com/coreos/go-oidc/MAINTAINERS
vendor/github.com/coreos/go-oidc/NOTICE
vendor/github.com/coreos/go-oidc/README.md
vendor/github.com/coreos/go-oidc/code-of-conduct.md
vendor/github.com/coreos/go-oidc/example/README.md
vendor/github.com/coreos/go-oidc/example/idtoken/app.go
vendor/github.com/coreos/go-oidc/example/nonce/app.go
vendor/github.com/coreos/go-oidc/example/userinfo/app.go
vendor/github.com/coreos/go-oidc/jose.go
vendor/github.com/coreos/go-oidc/jwks.go
vendor/github.com/coreos/go-oidc/jwks_test.go
vendor/github.com/coreos/go-oidc/oidc.go
vendor/github.com/coreos/go-oidc/oidc_test.go
vendor/github.com/coreos/go-oidc/test
vendor/github.com/coreos/go-oidc/verify.go
vendor/github.com/coreos/go-oidc/verify_test.go

vendor: add go-oidc

---

cmd/telemeter-server/main.go
deploy/telemeter-server.yaml
pkg/oauth2/token_source.go
pkg/oauth2/token_source_test.go

This adds OIDC support for authn/authz against tollbooth.
cc @squat @jfchevrette

oidc for tollbooth

---

jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet

jsonnet: cleanup telemeter client

---

jsonnet/jsonnetfile.lock.json
jsonnet/telemeter/server/kubernetes/kubernetes.libsonnet
manifests/server/list.yaml
manifests/server/statefulSet.yaml

@s-urbaniak this fixes a crucial parameter needed to establish the telemeter server cluster.

Fix gossip join parameter

---

jsonnet/jsonnetfile.lock.json
jsonnet/telemeter/prometheus/kubernetes/list.libsonnet
jsonnet/telemeter/server/kubernetes/kubernetes.libsonnet
manifests/prometheus/list.yaml
manifests/server/list.yaml
manifests/server/service.yaml

This PR fixes two jsonnet typos in the rendered lists.
cc @s-urbaniak

fix two jsonnet typos

---

pkg/authorize/stub/stub.go
pkg/authorize/tollbooth/mock.go
pkg/fnv/hash.go
pkg/fnv/hash_test.go
pkg/store/diskstore/diskstore.go

Fixes https://github.com/openshift/telemeter/pull/47#discussion_r225924456
/cc @squat

pkg/authorize: use centralized fnv hash

---

cmd/telemeter-client/main.go
jsonnet/jsonnetfile.lock.json
jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
manifests/client/secret.yaml

Add a default URL value for the `--to` flag of the telemeter client.
cc @s-urbaniak

Default to url

---

jsonnet/jsonnetfile.lock.json
jsonnet/telemeter/server/kubernetes/kubernetes.libsonnet
manifests/server/list.yaml
manifests/server/serviceAccount.yaml

fixes: https://github.com/openshift/telemeter/issues/65
cc @jfchevrette @s-urbaniak

Add ServiceAccount to telemeter server

---

build_deploy.sh
dockerfiles/Dockerfile.build
dockerfiles/Dockerfile.deploy
dockerfiles/README.txt

This script using single stage build and pushes to quay.io

Adds build-deploy.sh script for CI integration

---

jsonnet/jsonnetfile.lock.json
jsonnet/telemeter/server/kubernetes/kubernetes.libsonnet
manifests/server/list.yaml
manifests/server/statefulSet.yaml

 jsonnet: do not render volumeClaimTemplates

---

jsonnet/jsonnetfile.lock.json
jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
manifests/client/deployment.yaml
manifests/client/servingCertsCABundle.yaml

*: update use of service certs ca bundle

---

jsonnet/jsonnetfile.lock.json
jsonnet/telemeter/prometheus/kubernetes/kubernetes.libsonnet
manifests/prometheus/list.yaml
manifests/prometheus/route.yaml

cc @s-urbaniak @riuvshin 
ref: https://github.com/tnozicka/openshift-acme/blob/master/docs/design/architecture.adoc#managed-objects

name route certs secret

---

pkg/cluster/cluster.go
pkg/cluster/cluster_test.go

Currently, once a node is marked as problematic, it will never be
marked as not problematic if the problems count is >4.
This fixes it by unsetting the problematic node after the expiration
date.
Fixes MON-392
cc @squat @brancz

pkg/cluster: consider nodes not problematic after expiration

---

jsonnet/jsonnetfile.lock.json
jsonnet/telemeter/server/kubernetes/kubernetes.libsonnet
manifests/server/list.yaml
manifests/server/serviceMonitor.yaml
manifests/server/serviceMonitorFederate.yaml

jsonnet: use internal endpoint for telemeter servicemonitors

---

jsonnet/jsonnetfile.lock.json
jsonnet/telemeter/server/kubernetes/kubernetes.libsonnet
manifests/server/list.yaml
manifests/server/service.yaml
manifests/server/statefulSet.yaml

jsonnet: fix swapped internal/cluster ports

---

cmd/telemeter-server/main.go

Wrap the cluster store within a rate-limited store.
This guarantees an upper-bound on the total
inter-node requests that hit the target node of `l*n`, where l is the
rate limit and n is the cluster size. Without this, if a DOS attack
with IDs that hash to node A's bucket enter the cluster on different
node, node B, then node B will dutifully pass along the requests to
the node A and can DOS the target and congest the internal network.
cc @s-urbaniak @brancz

cmd/telemeter-server: improve rate limiting

---

pkg/metricfamily/label.go

This commit introduces a mutex lock in the label transformer to ensure
that mutable state is not accessed concurrently.
cc @s-urbaniak addresses your comment https://github.com/openshift/telemeter/pull/101#discussion_r238182816

pkg/metricfamily: lock label transformer

---

jsonnet/telemeter/metrics.jsonnet

cc @s-urbaniak @smarterclayton

jsonnet: put metrics into jsonnet format to simplify

---

jsonnet/telemeter/server/kubernetes.libsonnet
manifests/server/list.yaml
manifests/server/statefulSet.yaml

Fix quoting of `--whitelist` argument quoting in Telemeter server.
cc @jfchevrette @s-urbaniak

jsonnet: fix argument quoting

---

jsonnet/telemeter/prometheus/kubernetes.libsonnet
manifests/prometheus/list.yaml
manifests/prometheus/service.yaml

 jsonnet: add session affinity to prom svc

---

jsonnet/telemeter/server.libsonnet
jsonnet/telemeter/server/kubernetes.libsonnet
manifests/server/list.yaml
manifests/server/statefulSet.yaml

Depends on #146 to be merged first
cc @squat

jsonnet/telemeter: elide prometheus_replica label

---

jsonnet/telemeter/lib/list.libsonnet
jsonnet/telemeter/prometheus.libsonnet
jsonnet/telemeter/prometheus/kubernetes.libsonnet
jsonnet/telemeter/server.libsonnet
jsonnet/telemeter/server/kubernetes.libsonnet
manifests/prometheus/list.yaml
manifests/prometheus/prometheus.yaml
manifests/server/list.yaml
manifests/server/statefulSet.yaml

- Add resource requests and limits variables to telemeter server
- Add resource requests and limits variables to prometheus
- Allow setting the resource requests and limits via the templates

Add resource limits to telemeter server and prometheus

---

.gitignore
.travis.yml
Makefile

Same as #175. Creating second PR to get rid of failing CI status check.
Align build process with one known from other projects maintained by monitoring team, mainly openshift/cluster-monitoring-operator and coreos/prometheus-operator.
Propagation of work from https://github.com/openshift/cluster-monitoring-operator/pull/351

Add Travis config and use containerized jsonnet

---

pkg/store/ratelimited/ratelimited.go

cc @s-urbaniak @metalmatze @aditya-konarde

pkg/store: fix ratelimited err overflow

---

jsonnet/telemeter/prometheus/kubernetes.libsonnet
manifests/prometheus/list.yaml
manifests/prometheus/serviceMonitor.yaml

Fix : https://github.com/openshift/telemeter/issues/180

Honor labels in telemeter prometheus

---

jsonnet/telemeter/client/kubernetes.libsonnet
manifests/client/deployment.yaml

Adding http proxy variables.
Blocks https://github.com/openshift/cluster-monitoring-operator/pull/404

Add support for HTTP proxy env vars

---

Makefile
test/benchmark.sh

This commit adds a goal argument to the benchmark script. Now, any
benchmarking test that does not meet the specified goal will exit
non-zero.

test/benchmark: test goal

---

OWNERS

Member is no longer with this project.

Remove riuvshin from owners

---

OWNERS

OWNERS: Add lilic

---

cmd/telemeter-server/main.go

@squat @kakkoyun @metalmatze @ant31

telemeter-server: Fix receive path

---

.errcheck_excludes.txt
.golangci.yml
Makefile
cmd/authorization-server/main.go
cmd/telemeter-benchmark/main.go
cmd/telemeter-client/main.go
cmd/telemeter-server/main.go
cmd/telemeter-server/main_test.go
go.mod
go.sum
pkg/authorize/handler.go
pkg/authorize/jwt/handler.go
pkg/authorize/jwt/handler_test.go
pkg/authorize/jwt/validator.go
pkg/authorize/tollbooth/mock.go
pkg/authorize/tollbooth/tollbooth.go
pkg/benchmark/benchmark.go
pkg/cluster/cluster.go
pkg/cluster/cluster_test.go
pkg/cluster/memberlist.go
pkg/forwarder/forwarder.go
pkg/forwarder/forwarder_test.go
pkg/http/roundtripper.go
pkg/http/server/server.go
pkg/logger/logger.go
pkg/metricsclient/metricsclient.go
pkg/receive/handler.go
pkg/store/forward/forward.go
test/e2e/forward_test.go
vendor/modules.txt

This PR introduces structured logging and removes usage of the standard logger to improve troubleshooting experience.

Add structured logging

---

jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json

Since we now run generate as part of CI, this should fix it hopefully.
cc @brancz @paulfantom

jsonnet/: Use local directory

---

jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
jsonnet/telemeter/prometheus/kubernetes.libsonnet
manifests/prometheus/list.yaml
manifests/prometheus/serviceAccount.yaml

We need to add this annotation for the serving certs to appear.
/cc @aditya-konarde @brancz @kakkoyun @squat

Add jaeger-oauth annotation on serviceaccount

---

jsonnet/jsonnetfile.lock.json
jsonnet/telemeter/jsonnetfile.json
manifests/benchmark/clusterRoleBindingPrometheusOperator.yaml
manifests/benchmark/deploymentPrometheusOperator.yaml
manifests/benchmark/serviceAccountPrometheusOperator.yaml

cc @openshift/openshift-team-monitoring

jsonnet,manifests: Bump prometheus-operator to 0.34

---

README.md

README.md: Add basic info on how to add new metrics

---

OWNERS

cc @bwplotka @brancz @kakkoyun @metalmatze

OWNERS: add bartek

---

jsonnet/telemeter/server/kubernetes.libsonnet

cc @kakkoyun @metalmatze @brancz @bwplotka

jsonnet/telemeter: ensure tag in memcached

---

docs/data-collection.md
jsonnet/telemeter/metrics.jsonnet
jsonnet/telemeter/prometheus/kubernetes.libsonnet
jsonnet/telemeter/rules.libsonnet

Add first Telemeter recording rules

---

jsonnet/telemeter/benchmark/kubernetes.libsonnet
manifests/benchmark/statefulSetTelemeterServer.yaml

jsonnet: use stable APIS in benchmark manifests

---

jsonnet/telemeter/prometheus/kubernetes.libsonnet
manifests/prometheus/list.yaml
manifests/prometheus/serviceAccount.yaml

This PR adds necessary annotation for new Observatorium API route to the service account
cc @metalmatze

Add annotation for new Observatorium API Route

---

test/integration-v2.sh

Occasionally, our integration tests are flaking because a process
listening on a certain port in the first integration test has not exited
before another process tries to listen on that port in the second
integration test. This commit gives the processes in the second
integration test a separate set of ports to ensure that the integration
tests do not conflict with one-another.
cc @metalmatze

test/integration: fix already used port race

---

jsonnet/telemeter/server/kubernetes.libsonnet

@metalmatze @squat 
cc @maorfr

jsonnet: Ensure env var is actually added

---

jsonnet/telemeter/server/kubernetes.libsonnet

Bug 1813894: Stop using service ca from service account token

---

jsonnet/telemeter/lib/list.libsonnet

Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>

don't set tls server name with insecureSkipVerify

---

cmd/telemeter-server/main.go

Enable forwardClient InstrumentedRoundTripper

---

cmd/telemeter-server/main.go

/cc @squat 
Depends on #344 to be merged first.

Enable forward roundtripper auth

---

jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
jsonnet/telemeter/client/kubernetes.libsonnet
manifests/client/deployment.yaml
manifests/prometheus/list.yaml

This is a backport of #320.
cc @openshift/openshift-team-monitoring

Bug 1818806: jsonnet/telemeter: set cpu requests, unset limits

---

jsonnet/telemeter/rules.libsonnet

https://github.com/open-cluster-management/backlog/issues/6365

Bug 1919360: Add ACM Managed cluster reporting rule

---

jsonnet/telemeter/rules.libsonnet

Leverage knowledge about what resources are provided by a plugin
to categorize the usage of those plugins at a cluster _id level.
This is primarily accurate in late 4.6/4.7+ due to telemetry
including these resources. This categorized a significant chunk
of clusters although there are some edge cases noted.

jsonnet/telemeter: Add a recording rule that captures network_type

---

go.mod
go.sum
pkg/forwarder/forwarder.go
vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
vendor/github.com/prometheus/client_golang/prometheus/go_collector_go116.go
vendor/github.com/prometheus/client_golang/prometheus/go_collector_latest.go
vendor/github.com/prometheus/client_golang/prometheus/internal/go_runtime_metrics.go
vendor/modules.txt

It helps detecting whether the telemeter client is successful or not.

pkg/forwarder: add counter for the total number of requests

---

go.mod
go.sum
vendor/github.com/gogo/protobuf/proto/text_parser.go
vendor/github.com/gogo/protobuf/types/any.pb.go
vendor/github.com/gogo/protobuf/types/api.pb.go
vendor/github.com/gogo/protobuf/types/duration.pb.go
vendor/github.com/gogo/protobuf/types/empty.pb.go
vendor/github.com/gogo/protobuf/types/field_mask.pb.go
vendor/github.com/gogo/protobuf/types/source_context.pb.go
vendor/github.com/gogo/protobuf/types/struct.pb.go
vendor/github.com/gogo/protobuf/types/timestamp.pb.go
vendor/github.com/gogo/protobuf/types/type.pb.go
vendor/github.com/gogo/protobuf/types/wrappers.pb.go
vendor/golang.org/x/tools/go/ast/astutil/util.go
vendor/golang.org/x/tools/go/internal/gcimporter/gcimporter.go
vendor/modules.txt

Signed-off-by: Jan Fajerski <jfajersk@redhat.com>

Bug 1924548: go.mod: update github.com/gogo/protobuf to v1.3.2

---

pkg/server/forward.go

This PR adds back the `telemeter_v1_forward_requests_total` metric to keep track of the number of forwarded requests to `/upload` endpoint.
This also changes label values of this metric to, 
- `telemeter_error`: To indicate errors during metric family -> remote write request conversion
- `success`/`error`: To indicate success/failure once request is forwarded to Receive.

pkg/server: use v1 forward requests counter

---

OWNERS

This PR adds me to the owners file. 🙂

OWNERS: Add myself to owners file

---

jsonnet/telemeter/rules.libsonnet

cc @kahowell @barnabycourt @taneem-ibrahim
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>

Add rules for cluster vCPU-hours 

---

pkg/receive/handler.go

Similar to https://github.com/openshift/telemeter/pull/429, adding label sanitization to the Telemeter server receive path,
as we need to ensure this for Thanos Receive with versions > `v0.28`.

pkg/receive: Sanitize metric labels

---

pkg/authorize/handler.go
pkg/receive/handler.go

This PR allows logging any faulty tokens or authorization headers.

Log faulty tokens

---

go.mod
go.sum
pkg/receive/handler.go
test/integration-v2.sh
vendor/github.com/golang/snappy/AUTHORS
vendor/github.com/golang/snappy/CONTRIBUTORS
vendor/github.com/golang/snappy/decode.go
vendor/github.com/golang/snappy/decode_arm64.s
vendor/github.com/golang/snappy/decode_asm.go
vendor/github.com/golang/snappy/decode_other.go
vendor/github.com/golang/snappy/encode.go
vendor/github.com/golang/snappy/encode_arm64.s
vendor/github.com/golang/snappy/encode_asm.go
vendor/github.com/golang/snappy/encode_other.go
vendor/modules.txt

Bumps snappy version to latest and adds some debug logs to verify empty remote write requests
cc: @PhilipGough

Bump snappy version and add debug logs

---

pkg/receive/handler.go

This PR fixes the receive path whitelist logic to return true on __any__ whitelist match instead of all.

Fix receive whitelist logic

---

cmd/telemeter-server/main.go

Attempts to solve the problem described in https://issues.redhat.com/browse/RHOBS-545
TL;DR is that in production, we are experiencing log spam coming from some probe in the OpenShift ingress HAProxies

Filter noisy logs from TCP probes

---

Makefile

Fix path benchmark
make test/timeseries.txt  is nor working due a change in path

Fix path benchmark

---

jsonnet/telemeter/rhelemeter.libsonnet
jsonnet/telemeter/server/rhelemeter-kubernetes.libsonnet

https://issues.redhat.com/browse/RHOBS-789

jsonnet: Add config to support rhelemeter

---

cmd/rhelemeter-server/main.go
cmd/rhelemeter-server/main_e2e_test.go
cmd/rhelemeter-server/testdata/client-info.json
pkg/authorize/ssl/ssl.go
pkg/authorize/ssl/ssl_test.go

https://issues.redhat.com/browse/RHOBS-855

RHOBS-855: rhelemeter: Read client info/data from request

---

pkg/authorize/handler.go

As a result of a previous change, 403 returned by the authorization server now result in 500 returned to the client. This triggers retries and alerts from our monitoring system.
This PR reverts to the previous behaviour.

Fix: handle authorization server 403 responses

---

go.mod

Bump golang 1.20

---

jsonnet/telemeter/rules.libsonnet

To cater for https://gitlab.cee.redhat.com/service/uhc-account-manager/-/commit/b20bdbdf0fe3a9d1b5804f3db2a5fe0f37248faa

RHOBS-956: Rename subscription_labels to ocm_subscription

---

jsonnet/telemeter/rules.libsonnet
test/rulestests.yaml

The related issue: https://issues.redhat.com/browse/MON-3890

MON-3890: add recording rule acm_capacity_effective_cpu_cores

---

jsonnet/telemeter/rules.libsonnet

Taking care of some comments coming from this PR:
https://github.com/openshift/telemeter/pull/544

OSD-25491 & OSD-25492: Comments fix
