- cmd/telemeter-client/main.go
- cmd/telemeter-server/main.go
- pkg/authorizer/server/server.go
- test/integration.sh
Switch authentication from using `?cluster=` to `?id=`, and set the
default partition key to `_id` to avoid conflicts with user provided
labels.
> Provide a default --to flag for clients, use --id for identifier

- cmd/telemeter-client/main.go
- deploy/default-rules
- pkg/transform/transform.go
- test/integration.sh
Prometheus treats `ALERTS` as a special series, but that data may be something to gather for historical purposes. Support `--rename` with a default value of `ALERTS=alerts`, add it to default-rules, and add an integration test.
> Capture alerts but rename them before sending

- cmd/telemeter-server/main.go
- pkg/http/server/server.go
This helps us with back-of-the-envelope calculating the expected
request sizes.
/cc @smarterclayton @brancz
> cmd/telemeter-server: register handler request size metrics

- test/integration.sh
tiny typo I stumbled upon. This test is checking the metrics for `scraped`, not `build_info`
> test: fix integration test typo

- cmd/authorization-server/main.go
- pkg/authorizer/authorizer.go
- pkg/authorizer/server/server.go
We do not need to export the type `savedResponse` for unmarshalling as
long as the fields are exported [0].
[0] https://play.golang.org/p/HvkSjCEuxr4
> cmd,pkg: fix some golint rules

- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
- manifests/telemeter-client-deployment.yaml
- manifests/telemeter-client-secret.yaml
This PR puts the telemeter server URL into a secret and loads it into the container using an environment variable. This has the benefit of being easier to override in actual deployments by simple modifying the underlying secret rather than needing to iterate over the flags and modifying the one with the URL.
This helps address: https://github.com/openshift/cluster-monitoring-operator/pull/103#discussion_r220598831
cc @s-urbaniak @brancz
> jsonnet: put telemeter server URL into secret and env var

- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/client/telemeter-client.libsonnet
This PR corrects an issue where the jobs field in the config was being overwritten rather than extended.
addresses: https://github.com/openshift/cluster-monitoring-operator/pull/103#discussion_r220684050
cc @brancz @s-urbaniak
> jsonnet: extend jobs with telemeter client

- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
- manifests/telemeter-client-clusterRole.yaml
- manifests/telemeter-client-clusterRoleBinding.yaml
- manifests/telemeter-client-deployment.yaml
- manifests/telemeter-client-serviceAccount.yaml
In order to authenticate against a Prometheus k8s pod created by the Cluster Monitoring Operator, the bearer token must belong to a ServiceAccount with the following SAR `{"resource":"namespaces","verb":"get"}` [0]
[0] https://github.com/openshift/cluster-monitoring-operator/blob/master/jsonnet/prometheus.jsonnet#L290
cc @s-urbaniak
> add service account with correct roles to telemeter-client

- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
- manifests/telemeter-client-clusterRole.yaml
- manifests/telemeter-client-deployment.yaml
- manifests/telemeter-client-service.yaml
- manifests/telemeter-client-serviceMonitor.yaml
Currently, nothing can scrape the Telemeter clients metrics because it is only listening on localhost. In order to expose the Telemeter client's metrics to a prometheus server, we must allow other pods to access its `/metrics` endpoint. However, the Telemeter client can potentially expose sensitive user data on its metrics endpoint. For this reason, we need to add a proxy that exposes the metrics endpoint only to authorized applications.
cc @s-urbaniak
> secure telemeter client with rbac proxy

- deploy/telemeter-server.yaml
- deploy/telemeter.secret.yaml
This adds a sample secret resource as well as link to the values as env variables in the telemeter-server deployment.
> Add RHD credentials to deploy configs

- deploy/telemeter-client-openshift.yaml
- deploy/telemeter-client.yaml
https://github.com/openshift/release/blob/9c980ba/ci-operator/templates/cluster-launch-e2e.yaml#L132
points to the client which is supposed to be deployed during a e2e
test.
Currently, v3.11 telemeter clients are deployed, but it should be
v4.0.
This fixes it.
/cc @squat
> deploy: bump telemeter-client for api.ci

- Makefile
- jsonnet/jsonnetfile.json
- jsonnet/jsonnetfile.lock.json
- jsonnet/prometheus.jsonnet
- jsonnet/telemeter/prometheus/kubernetes/kubernetes.libsonnet
- jsonnet/telemeter/prometheus/kubernetes/list.libsonnet
- jsonnet/telemeter/prometheus/prometheus-telemeter.libsonnet
- jsonnet/telemeter/server/kubernetes/list.libsonnet
- manifests/prometheus/clusterRole.yaml
- manifests/prometheus/clusterRoleBinding.yaml
- manifests/prometheus/htpasswdSecret.yaml
- manifests/prometheus/list.yaml
- manifests/prometheus/prometheus.yaml
- manifests/prometheus/proxySecret.yaml
- manifests/prometheus/roleBindingConfig.yaml
- manifests/prometheus/roleBindingSpecificNamespaces.yaml
- manifests/prometheus/roleConfig.yaml
- manifests/prometheus/roleSpecificNamespaces.yaml
- manifests/prometheus/route.yaml
- manifests/prometheus/rules.yaml
- manifests/prometheus/service.yaml
- manifests/prometheus/serviceAccount.yaml
- manifests/prometheus/serviceMonitor.yaml
This PR adds the jsonnet files necessary to generate the prometheus statefulset that scrapes the telemeter server (AKA the "insights" prometheus). The PR also commits the generated yaml files.
I have tested deploying the generated files against a 3.10 openshift cluster and everything works as expected :tada:!!
In order to finish the work of scraping the telemeter server, we need to create a ServiceMonitor manifest for it.
cc @s-urbaniak @jmelis @pbergene
> add jsonnet for prometheus

- cmd/telemeter-server/main_test.go
- pkg/http/server/server.go
- pkg/http/server/server_test.go
- pkg/metricfamily/drop_timestamp.go
- pkg/metricfamily/drop_timestamp_test.go
Currently, timestamps are preserved from the most recent client push.
In case of telemeter client push failures this causes metrics scraped from telemeter server
to report the same timestamp of the most recently pushed metrics until either:
a) the client subsequently pushes new metrics successfully,
effectively updating the timestamp of the most recently pushed metrics.
or
b) after a 10 minute window the most recently pushed metric is being removed.
Prometheus, when scraping metrics including timestamps, does not consider them to be stale
if the timestamp between does not change, but they are removed from the graph after 5 minutes
(not configurable) effectively disabling the above 10 minute window.
This fixes it by not forwarding metric timestamps.
Prometheus in that case will consider …
> pkg/http/server: drop metric timestamps on federate

- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
- manifests/client/clusterRole.yaml
- manifests/client/clusterRoleBindingView.yaml
This commit changes the Telemeter client configuration to bind against
an existing `cluster-monitoring-view` ClusterRole, rather than creating
a ClusterRole that duplicates this one. The reasoning for this is that
if the definition of the permissions required for the
`cluster-monitoring-view` change, then the Telemeter code base does not
need to change.
cc @brancz @s-urbaniak 
addresses: https://github.com/openshift/telemeter/pull/35#issuecomment-429854862
>  jsonnet: reference cluster-monitoring-view

- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
- manifests/client/deployment.yaml
- manifests/client/secret.yaml
This commit adds support for using a salt to anonymize metrics reported
by the client.
cc @s-urbaniak
> jsonnet/telemeter/client: add support for salt

- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/server/kubernetes/kubernetes.libsonnet
- manifests/server/list.yaml
- manifests/server/statefulSet.yaml
This PR re-introduces the `NAME` environment variable, which was accidentally omitted.
cc @jfchevrette @s-urbaniak 
fixes: https://github.com/openshift/telemeter/issues/68
> jsonnet/telemeter/server: re-add name env var

- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/prometheus/kubernetes/list.libsonnet
- jsonnet/telemeter/prometheus/prometheus-telemeter.libsonnet
- manifests/prometheus/list.yaml
This enables permissions (subject access review as well as delegate URLs)
to be configured using saas hurder template variables.
cc @squat
> jsonnet/prometheus: configure permissions

- test/integration.sh
A few errors prevented it from working. Drop unsupported args, switch
to the new tokens.json file, and allow `TEST=` to leave the local
test cluster.
> test: Update the integration test to deal with entropy

- deploy/default-rules
- jsonnet/telemeter/client/metrics.json
openshift/cluster-version-operator#45 and openshift/cluster-version-operator#47
added a set of core metrics to the cluster version operator to report on the
version of the cluster, the health of the cluster operators, and any payload
errors. As these metrics are of key importance to safe rollout of automated
upgrades to a cluster, gather and report them to telemetry.
These metrics have limited privacy impact when gathering since we only track
version strings. A future release may return the payload image used to carry
the update, which might include local registry information.
See https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/metrics.md for a description of the metrics being captured.
@derekwaynecarr
> rules: Gather cluster version metrics from a cluster

- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
- manifests/client/deployment.yaml
This PR finalizes support for the new Service Certs CA Bundle interface
by adding a configmap reload container to the Telemeter client Pod.
This container will watch the CA bundle volume and POST to the Telemeter
client's new `/-/reload` endpoint to trigger a reconfiguration of the container.
Note: this PR uses the v3.11 tag of the configmap-reload container as there
is currently no v4.0 image. Once that image is built, we should bump this.
cc @s-urbaniak @brancz
> Add Configmap Reload to client

- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/prometheus/kubernetes/kubernetes.libsonnet
- jsonnet/telemeter/server/kubernetes/kubernetes.libsonnet
- manifests/prometheus/list.yaml
- manifests/prometheus/prometheus.yaml
- manifests/server/list.yaml
- manifests/server/serviceMonitorFederate.yaml
This commit adds a new ServiceMonitor object that is configured to
scrape the Telemeter server `/federate` endpoint. It also reconfigures
the Prometheus object to only match ServiceMonitors that specify a
federation label.
cc @s-urbaniak
> Scrape Federate Endpoint

- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/client/kubernetes/kubernetes.libsonnet
- manifests/client/deployment.yaml
- manifests/client/servingCertsCABundle.yaml
Burned again by the ksonnet constructors :p
This commit fixes the definition of the Volume for the serving certs CA
bundle ConfigMap. Instead of specifying a list of key-path pairs to
load explicitly, we let the Volume load all keys from the ConfigMap.
Unfortunately the Volume constructor for ConfigMaps requires a list of
items, so we bypass the constructor and use the mixins to generate the
volume.
cc @s-urbaniak
> jsonnet/telemeter/client: fix configMap volume

- cmd/telemeter-server/main.go
- cmd/telemeter-server/main_test.go
- pkg/authorize/jwt/handler.go
- pkg/authorize/jwt/handler_test.go
- pkg/http/server/server.go
- pkg/http/server/server_test.go
- pkg/metricfamily/multi_transformer.go
- pkg/validate/validator.go
This commit fixes the handling of required labels in the JWT package.
Formerly, the JWT authorizer constructor accepted a labels parameter,
but this map was never actually used by the type. This commit fixes the
handling of the parameter so that the labels are added to the JWT. This
means that the labels will now be respected as required labels in the
validator.
This commit also cleans up some general label handling. For example, the
validator was had the responsibility of adding additional labels
to the received metrics, when this really has nothing to do with
validation; it is instead a general purpose transformation. This has
been extracted and put instead into the `Post` handler so that the label
addition occurs after successful validation.
cc @s-urbaniak
> pkg/authorize/jwt: fix handling of required labels

- pkg/forwarder/forwarder.go
- pkg/forwarder/forwarder_test.go
This commit adjusts the logic of the forwarder to allow no anonymization
labels to be specified. If this is done, a warning will be logged. It is
still disallowed to specify labels with no salt.
cc @s-urbaniak
> pkg/forwarder: allow no labels to be anonymized

- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/lib/list.libsonnet
- jsonnet/telemeter/prometheus.libsonnet
- manifests/prometheus/list.yaml
- manifests/server/list.yaml
Saasherder requires the `IMAGE_TAG` variable to be defined in the
template, so use this to write in the generated build tag for Telemeter
server. Also, introduce a placeholer variable for the Prometheus
template. Once Saasherder fixes these semantics, we can remove this.
cc @riuvshin @s-urbaniak
>  jsonnet/telemeter: accomodate saasherder

- cmd/telemeter-client/main.go
- pkg/forwarder/forwarder.go
These commits make some small improvements:
1. actually enable verbose logging on the client
2. simplify composition of transforms in the client forwarder
cc @s-urbaniak
> cmd,pkg: small improvements

- cmd/telemeter-client/main.go
- cmd/telemeter-server/main.go
- pkg/http/server/server.go
- pkg/metricfamily/expired.go
- pkg/store/memstore/memstore.go
- pkg/store/memstore/memstore_test.go
- test/integration.sh
cmd/telemeter-client: add ttl, ratelimit cmdline parameters
This adds TTL and ratelimit settings as command line parameters.
pkg/store/memstore: implement copy-on-read
Currently, all metrics families read from the memory store are returned by
reference. Callers can (and are) modify them in an unsynchronized manner,
thus manipulating the memory store's internal state.
This fixes it by cloning the returned metrics families.
pkg/http/server: pass max sample age without conversion
max sample age is currently passed as a millisecond value, while
NewDropExpiredSamples expectes them to be in time.Time format.
This fixes it.
cc @squat
> cmd/telemeter-client: add ttl, ratelimit cmdline parameters

- jsonnet/telemeter/client/kubernetes.libsonnet
I was checking out latest cluster-monitoring-operator on OpenShift, and saw that telemeter was not successfully being scraped with a certificate error:
I dug and found that kube-rbac-proxy was showing errors on requests (just an excerpt, but all log lines ever logged look like this):
```
2018/12/03 16:31:42 http: TLS handshake error from 10.129.0.12:48340: remote error: tls: bad certificate
2018/12/03 16:31:46 http: TLS handshake error from 10.128.0.39:43970: remote error: tls: bad certificate
2018/12/03 16:32:12 http: TLS handshake error from 10.129.0.12:48514: remote error: tls: bad certificate
```
So I looked at the config and found this subtle difference between the other `ServiceMonitor`s using the `service-ca.crt`.
@s-urbaniak @squat @metalmatze
> Fix ca bundle used to talk to telemeter client for metrics

- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/lib/list.libsonnet
- manifests/prometheus/list.yaml
This commit fixes the definition of the SAR for the proxy sitting in
front of the Telemeter Prometheus. The SAR was specifying an undefined
field `resourceName`, which was turning the SAR into `get namespace *`
rather than `get namespace $(NAMESPACE)`, which would fail.
This commit also removes the `namespace` field from the SAR, since
namespaces themselves are not namespaced objects.
This is currently breaking programmatic access via ServiceAccount tokens
to the Telemeter Prometheus instance in production.
cc @s-urbaniak @pbergene
>  jsonnet: fix prometheus SAR

- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/lib/list.libsonnet
- manifests/prometheus/list.yaml
This commit ensures that the non-namespaced objects in the generated
template manifests will not conflict when they are created in the
same cluster. Currently, if we create a ClusterRoleBinding templated for
production and later another for staging, the ClusterRoleBinding for
staging will stomp on the binding against the production ServiceAccount.
This ensures that the names of such objects will include the
namespace name.
cc @pbergene @s-urbaniak
> jsonnet: namespace non-namespaced objects

- Makefile
The Telemeter project includes a large number of automatically generated
files. In order to ensure that these files are always up to date, this
commit introduces a test to check that there is no diff after making all
the generated targets.
This commit will be followed up by a pull request to CI configuration
for this repository.
cc @s-urbaniak
> Makefile: create generate test

- Makefile
- docs/data-collection.md
This commit uses the embedmd utility, which we use in other monitoring
team projects, to embed code in Markdown docs and keep the code
up-to-date with source code in the repository.
cc @s-urbaniak
> Makefile,docs: embed jsonnet in docs

- Makefile
- jsonnet/telemeter/client/kubernetes.libsonnet
This PR ensures that the Telemeter client RBAC proxy can specify a TLS cipher suite.
Note, the cipher suite is optionally added in to allow rendering the client without specifying
a cipher suite and not have the argument `--tls-cipher-suite=""`.
cc @brancz @s-urbaniak
> telemeter: add tls cipher suite

- jsonnet/telemeter/server/kubernetes.libsonnet
- manifests/server/list.yaml
- manifests/server/statefulSet.yaml
Telemeter Prometheus is showing holes in the graphs due to timeouts
while Prometheus is scraping Telemeter server, where it is taking
\>10s on occasion. This commit scales the replicas so we can distribute
the metrics across the hash ring and rendering the metrics takes less
time. It also bumps the rate-limit so platforms that report metrics
on behalf of clusters, e.g. CI won't get rate-limited.
@jfchevrette @smarterclayton @brancz
>  jsonnet/telemeter: bump rate-limit and replicas

- jsonnet/telemeter/server/kubernetes.libsonnet
- manifests/server/list.yaml
- manifests/server/statefulSet.yaml
Telemeter server is still rate-limiting CI.
This sets the rate-limit to 100 times the intended frequency.
If a cluster is making requests more than every two seconds,
the requests will fail. This will also allow clusters reporting
on behalf of others, e.g. CI, to make requests more often.
The long-term solution is to introduce per-ID limits, or
a whitelist of IDs that are not rate-limited.
cc @brancz @smarterclayton
>  jsonnet: bump server ratelimit

- jsonnet/telemeter/prometheus/kubernetes.libsonnet
- manifests/prometheus/list.yaml
- manifests/prometheus/roleSpecificNamespaces.yaml
This commit removes the role to get/list/watch nodes
for Prometheus. This was carried over from kube-prometheus
but is no longer required, even there.
cc @brancz @jfchevrette @pbergene
> jsonnet: remove role for nodes

- jsonnet/telemeter/lib/list.libsonnet
- manifests/prometheus/list.yaml
This commit fixes the SAR that the OAuth proxy uses.
When checking if an account has privileges over a particular
namespace, namespaces are treated as namespaced objects, meaning
the SAR requires a `namespace` field.
fixes: https://github.com/openshift/telemeter/issues/123
cc @s-urbaniak @jfchevrette
>  jsonnet: fix SAR

- jsonnet/telemeter/prometheus/kubernetes.libsonnet
- manifests/prometheus/list.yaml
- manifests/prometheus/prometheus.yaml
This adds 500Gi PVCs to prometheus replicas.
Commit contains both the jsonnet changes and the resulting manifest changes
> Add storage to prometheus

- jsonnet/telemeter/client/kubernetes.libsonnet
- manifests/client/deployment.yaml
- manifests/client/secret.yaml
This is the first part of fixing reloading of certain Telemeter client fields.
The next part will be a change in Cluster Monitoring Operator.
cc @s-urbaniak 
The Telemeter client should take some non-sensitive values directly from
the pod spec rather than from the secret. This way, if the values in the
pod spec are modified by the cluster-monitoring-operator, the pod will
be rolled. Otherwise, the operator would have to check for a changed
secret and then scale the pod down and up.
Note that introducing a config-reloader would not help in this case as
the values are taken from command-line arguments that are never re-read,
rather than read from files.
>  jsonnet: take some values from spec

- jsonnet/telemeter/prometheus/kubernetes.libsonnet
- manifests/prometheus/list.yaml
- manifests/prometheus/prometheus.yaml
Prometheus manifest is missing retention. 
15d is the current expectation since that is what we're running at the moment. I assume it was added manually on the running instance and that change was never propagated upstream.
> Add prometheus retention set to 15d

- OWNERS
As discussed with @s-urbaniak and @squat ; The SRE team needs access to the repo, in case of any emergency hotfixes, and for quicker turnaround on collaborations, among other things.
> Add SRE team to OWNERS

- pkg/store/instrumented/instrumented.go
- pkg/store/memstore/memstore.go
This adds some metrics to the memory for debugging potential leaks.
Currently, we are using a gauge instead of a counter for counting the total
amount of stored metrics.
This fixes it.
cc @squat @jfchevrette
> add metrics, use correct metric type in store

- cmd/telemeter-server/main.go
Currently the cleaner is not started, causing possible memory leaks.
This fixes it.
cc @squat
> cmd/telemeter-server: start memory store cleaner

- jsonnet/telemeter/jsonnetfile.json
This patch pins the Prometheus Operator version specified in the
`jsonnet/telemeter/jsonnetfile.json` file to `v0.29.0` instead of
`master`.
Both kube-prometheus [1] as well as telemeter-client [2] vendor
prometheus-operator [3] in their `jsonnetfile.json`. In addition both
kube-prometheus as well as telemeter-client are vendored by the
cluster-monitoring-operator [4]. kube-prometheus imports
prometheus-operator at reference `v0.29.0`, telemeter-client imports
prometheus-operator at reference `master`. This results in a version
conflict in the cluster-monitoring-operator.
[1] https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/jsonnet/kube-prometheus/jsonnetfile.json#L41
[2] https://github.com/openshift/telemeter/blob/master/jsonnet/telemeter/jsonnetfile.json# …
> jsonnet/telemeter: Pin Prometheus Operator version

- cmd/telemeter-server/main.go
- pkg/metricfamily/elide.go
- pkg/metricfamily/elide_test.go
- test/integration.sh
- test/prom-local.conf
This adds the label eliding feature.
A separate PR follows which enables this feature in the deployment.
Fixes partially MON-516
> pkg/metricfamily: add elide transformer

- pkg/forwarder/forwarder.go
When a `--match` flag is passed without also specifying a
`--match-file`, the match rules are ignored. This fixes it. Notable, the
`./test/integration.sh` test included both flags, so we never hit the
error scenario.
This error is blocking getting the new infra metrics working.
To get the new metrics working in production, we need to bump
the jsonnet telemeter dep in CMO, but that changes the flags to
telemeter client from `--match-file` to `--match` so we will see the log
```
2019/03/25 16:29:32 warning: no metrics to send, doing nothing
```
@s-urbaniak
> pkg/forwarder: fix match flag

- pkg/authorize/tollbooth/tollbooth.go
Currently, if clusters are not found, this is propagated via a 500 status code.
This fixes it by handling a 404 code explicitely.
Depends on https://gitlab.cee.redhat.com/service/uhc-account-manager/merge_requests/388
> pkg/authorize/tollbooth: handle 404 - cluster not found

- pkg/authorize/jwt/handler.go
Currently we still log all authorize failures, spamming the telemeter server logs.
This fixes it by reducing the logging to actionable errors, namely with http status code >= 500.
cc @squat @aditya-konarde: I recognized in production, that we indeed still log authorize failure, even if clusters are unknown. This should lower the noise on telemeter server logs in production.
> authorize/jwt/handler: log authorize failures for >= 500

- Makefile
The go-jsonnet project recently moved the location of the jsonnet binary
to the canonical`/cmd` directory.
> Makefile: fix install of go-jsonnet

- jsonnet/telemeter/prometheus/kubernetes.libsonnet
- manifests/prometheus/list.yaml
- manifests/prometheus/route.yaml
This commit changes the Telemeter Prometheus Route object to use the
client's source IP as the load balancing criteria. This will ensure that
all requests coming from the same client end up at the same Pod. #145
was intended to implement this feature but came up short because
OpenShift Routes do not connect directly to Services but rather to their
underlying Endpoints.
cc @jfchevrette @s-urbaniak
>  jsonnet: prometheus route balance source IP

- jsonnet/telemeter/client/kubernetes.libsonnet
- manifests/client/deployment.yaml
All cluster components are supposed to have the
"system-cluster-critical" priority class.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1624253 for telemeter client.
@squat @s-urbaniak @metalmatze @mxinden @paulfantom
> client: Set priority class

- jsonnet/telemeter/lib/list.libsonnet
- manifests/server/list.yaml
This changes the templates default values from 0 to sane(er) defaults.
This work around an issue we had where openshift (oc client?) considers `0` (request) to be lower than a value like `400Mi` (limit) (set by prometheus-operator) and refuses to deploy the pod. Setting actual values will avoid this corner case.
> Update server & prometheus templates default resources

- docs/sample-metrics.md
This commit fixes the formatting of the doc.
Without the newlines, you can actually read the `[embedmd]:# ...`.
cc @s-urbaniak @brancz
> docs/sample-metrics: fix formatting

- pkg/cluster/cluster.go
- pkg/cluster/cluster_test.go
- pkg/http/routes.go
- pkg/store/ratelimited/ratelimited.go
While running local workloads I tested for contention between locks.
There were two obvious contention points that could be removed easily
without risk:
store: Don't hold the mutex while writing metrics
We were holding the limiter lock while accessing the store, which is not
necessary because the store is already safe and the limiter is already a
synchronization point. Switch the lock to guard only the map.
Removes a significant source of contention from the path.
and
cluster: Avoid contention on write lock
A significant source of contentions in the block profile was the 
refreshRing call. Since reads dominate writes (100:1 or more) we should us
a RWMutex. Also, we don't need to refresh inline, so switch to a background
loop for refreshing.
Removes a source of contention when handling …
> Remove two major sources of contention from telemeter

- jsonnet/telemeter/client/kubernetes.libsonnet
- manifests/client/deployment.yaml
Specify telemeter client to be scheduled only on linux nodes.
/cc @brancz @squat @s-urbaniak
> jsonnet: add nodeSelector to telemeter client

- Makefile
- pkg/metricsclient/metricsclient.go
Currently function `withCancel` starts a goroutine which writes to `err` variable. Unfortunately in case where context is closed we want to write to the same variable before goroutine finishes. This causes a data race.
Fix ensures that we are only writing to `err` in goroutine and after it finishes we are reading `err` value.
Problem was observed in https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_telemeter/134/pull-ci-openshift-telemeter-master-unit/220
Ticket: MON-594
/CC: @metalmatze @s-urbaniak @squat
> pkg/metricsclient: fix data race when creating error message while closing context

- pkg/forwarder/forwarder.go
Currently, match rules will be appended to the query towards
Prometheus because the previous query is being reused.
This fixes it by resetting the raw query, before encoding it again
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1707681
> Bug 1707681: pkg/forwarder: fix ever growing URI

- jsonnet/telemeter/jsonnetfile.json
We want to pin kube-prometheus in the cluster-monitoring-operator to use the stable `release-0.1` branch. That branch of kube-proemtheus however already uses v0.30.0 of the Prometheus Operator and therefore this needs to be bump in here, because jsonnet-bundler cannot handle (and shouldn't) multiple version in the same repo.
/cc @s-urbaniak @squat
> Bump Prometheus Operator to v0.30.0 in jsonnet

- Makefile
We cannot download binaries with `go get` when go modules support is enabled as this is adding new dependencies to `go.mod`.
Temporary fix to unblock https://github.com/openshift/telemeter/pull/179. In the long run I will delete targets responsible for downloading binaries as they are already provided in CI container (quay.io/coreos/jsonnet-ci).
/cc @brancz @s-urbaniak @squat
> *: download build binaries without using go modules

- pkg/http/server/server.go
- pkg/store/ratelimited/ratelimited.go
- pkg/store/ratelimited/ratelimited_test.go
This commit ensures that the key being ratelimited is logged along with
the error so admins can diagnose who is causing problems.
cc @brancz @aditya-konarde @s-urbaniak
> pkg/store/ratelimited: log offending key

- cmd/telemeter-server/main.go
- pkg/oauth2/token_source.go
- pkg/oauth2/token_source_test.go
Currently, if telemeter assumes a refresh token is still valid, it will
treat errors from fetching an access token as fatal.
In reality, the authorization server might have reset our session and
invalidate the refresh token server-side despite still being valid.
In that case it returns a 400 status code.
This fixes it.
Fixes MON-690
/cc @brancz @squat @paulfantom
> pkg/oauth2: consider session cancellation

- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/jsonnetfile.json
- manifests/benchmark/clusterRoleBindingPrometheusOperator.yaml
- manifests/benchmark/deploymentPrometheusOperator.yaml
- manifests/benchmark/serviceAccountPrometheusOperator.yaml
This is required to resolve the version conflict of bumping kube-prometheus in the cluster-monitoring-operator.
@s-urbaniak @squat @paulfantom @metalmatze
> jsonnet: Bump prometheus-operator

- Makefile
This is to unblock things until https://github.com/golangci/golangci-lint/issues/575 gets fixed. This is similar to what's been done in https://github.com/prometheus/prometheus/pull/5658.
cc @paulfantom
> Makefile: unblock golangci-lint installation

- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/jsonnetfile.json
- manifests/benchmark/clusterRoleBindingPrometheusOperator.yaml
- manifests/benchmark/deploymentPrometheusOperator.yaml
- manifests/benchmark/serviceAccountPrometheusOperator.yaml
This is necessary to bump cluster-monitoring-operator's kube-prometheus (update on kube-prometheus still pending).
@s-urbaniak @paulfantom @squat @metalmatze
> Bump prometheus operator

- Makefile
- test/benchmark.sh
This PR cuts down flakes with:
* This commit doubles the amount of time that the benchmark suite will
wait for the Prometheus server to be ready on the cluster up to 200s.
Benchmark tests are flaking because occasionally Prometheus takes too
long to come up. If necessary, we can bump this further.
This PR speeds up the test by:
* This commit ensures that the benchmark test will begin and end with the
goal value. Formerly, the benchmark test would begin at 1000 and end at
the goal, allowing the runner to find the highest successful value;
however, this takes a very long time. Now, the test will start at 5000
and exit 0 or 1 depending on if the test succeeds.
cc @paulfantom @s-urbaniak
> test/benchmark: cut down flakes and speed up test

- jsonnet/telemeter/prometheus/kubernetes.libsonnet
- manifests/prometheus/list.yaml
- manifests/prometheus/serviceAccount.yaml
We need to update the annotations on the prometheus-telemeter to use its ServiceAccount for the Thanos querier too.
/cc @aditya-konarde @brancz @squat
> Add Route annotation to ServiceAccount for thanos-querier

- jsonnet/telemeter/benchmark.libsonnet
- manifests/benchmark/clusterRoleBindingPrometheusOperator.yaml
This commit changes the name of the benchmarking Prometheus Operator
cluster role binding. Today, this cluster role binding has the same name
as the cluster role binding for Prometheus Operator created by the
monitoring stack but a different subject.
The result is that on a regular OpenShift cluster, the
benchmarking CRB will be overwritten by the CMO. When the CRB is
overwritten, the benchmarking Prometheus-Operator no longer has the
correct privileges and crashloops. This causes flakiness in the
benchmarking tests: when the timing is right, the benchmarking
Prometheus Operator is able to create a Prometheus, and when the timing
is wrong, it is not able to create a Prometheus, causing the tests to
fail.
cc @paulfantom @metalmatze @aditya-konarde @s-urbaniak
>  jsonnet: change benchmark crb name

- pkg/authorize/token_store.go
Increase the token store authorizer timeout to avoid repeating requests during times of high load.
This should be a temporary change, we do not expect requests to take longer than 10s in the long term. We are making changes on the UHC/OCM end to achieve this after a recent service degradation:
1. Larger RDS instance size, database is currently a bottleneck: https://jira.coreos.com/browse/APPSRE-820
2. Profile database, collect performance information, and optimize DB queries: https://jira.coreos.com/browse/SDB-574
3. Setting sane http and DB connection limits: https://jira.coreos.com/browse/SDB-575
Postmortem is still on-going and further improvements may be necessary.
> Increase token store authorizer timeout to 30s

- cmd/telemeter-server/main.go
- vendor/golang.org/x/oauth2/clientcredentials/clientcredentials.go
- vendor/modules.txt
This change configures telemeter server to use the client credentials grant flow if the authorize username is unset.
This should make the transition to sso.redhat.com (using client credentials grant) from developers.redhat.com (using resource owner password credentials grant) very easy, by simply setting RHD_USERNAME to empty string `""`, and just reconfiguring RHD_CLIENT_ID, RHD_PASSWORD, and RHD_URL.
Fixes OBS-17
/cc @squat @jmelis @LiliC @ant31
> OBS-17: implement client credentials grant flow

- pkg/store/forward/forward.go
- pkg/store/forward/forward_test.go
For every failed request we will get the mean drift from the current timestamp. This should be helpful to find clusters that are way off.
/cc @squat @kakkoyun @brancz
> Log the mean drift from current timestamp when forward fails

- pkg/store/forward/forward.go
We want to also log clusters that ingest data being in the future with a mean more than 10s.
/cc @squat
> Log mean drift time for cluster more than 10s apart

- pkg/store/forward/forward.go
- pkg/store/forward/forward_test.go
This commit ensures that time series forwarded by telemeter server to a
remote-write endpoint will defensively have their timestamps
overwritten, ensuring that they are always increasing monotonically.
cc @metalmatze @brancz
> pkg/store/forward: defensively override timestamps

- pkg/store/forward/forward.go
Only overwrite timestamps that are in the future.
Also expose a metric to track how many timestamps are being overwritten.
cc @brancz @metalmatze
>  pkg/store/forward: only overwrite future timestamps

- pkg/store/forward/forward.go
This commit adds the Thanos tenant header to all requests forwarded to
the receive components. This will keep us prepared for when every tenant
has its own TSDB and will also help us track failures in the receive
component per tenant.
cc @brancz @metalmatze @kakkoyun
> pkg/store/forward: add tenant header

- jsonnet/telemeter/server/kubernetes.libsonnet
remove the username environment variable and arg from the telemeter-server statefulset so we can use the client-credentials grant flow.
cc @jmelis @metalmatze
> jsonnet/telemeter: remove auth username

- jsonnet/telemeter/jsonnetfile.json
kube-prom pins this version to release-0.30 release. Currently this is
causing conflicts when running jb update in CMO.
https://github.com/coreos/kube-prometheus/blob/release-0.1/jsonnet/kube-prometheus/jsonnetfile.json#L41
cc @brancz
> Bug 1732945:  jsonnet/telemeter/jsonnetfile.json: Adjust syncs

- pkg/benchmark/benchmark.go
- pkg/forwarder/forwarder.go
- pkg/metricsclient/metricsclient.go
Currently, requests to the in-cluster Prometheus respect the environment
variable proxy configuration just as requests to telemeter server
respect it. This means that when the proxy configuration is set,
requests to scrape the in-cluster prometheus will fail. This commit
fixes the configuration so only outbound requests are proxied.
cc @kakkoyun @metalmatze @s-urbaniak
> Bug 1744017: pkg/forwarder: dont proxy in-cluster requests

- cmd/telemeter-server/main.go
- pkg/authorize/client.go
- pkg/authorize/context.go
- pkg/authorize/handler.go
- pkg/authorize/jwt/handler.go
- pkg/authorize/tollbooth/tollbooth.go
- pkg/receive/handler.go
We want to add a remote-write receive handler to Telemeter.
For this we need to add a new authorizer, as we are unable to use JWTs.
Works with a mock authorization-server.
Here's a Prometheus config to test with:
```yaml
global:
scrape_interval:     15s
evaluation_interval: 15s
scrape_configs:
- job_name: 'prometheus'
static_configs:
- targets: ['localhost:9090']
- job_name: 'telemeter'
static_configs:
- targets: ['localhost:9004']
remote_write:
- url: "http://localhost:9003/metrics/v1/receive"
bearer_token: 'eyJjbHVzdGVyIjogImU1MGFiNGIwLTgwZjgtNDU3OC05NWVmLWQ0NzI5Njg5NzZhZSIsICJ0b2tlbiI6ICJhIn0K'
```
TODOs:
/cc @squat @brancz @kakkoyun
> Add a receive handler to Telemeter for remote-write

- jsonnet/telemeter/client/kubernetes.libsonnet
- manifests/client/deployment.yaml
The configmap reload for telemeter client was pointing to an unused port,
meaning that it would never reload anything.
cc @s-urbaniak @metalmatze @kakkoyun
> Bug 1746686: jsonnet: fix client reload port

- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/jsonnetfile.json
- manifests/benchmark/clusterRoleBindingPrometheusOperator.yaml
- manifests/benchmark/deploymentPrometheusOperator.yaml
- manifests/benchmark/serviceAccountPrometheusOperator.yaml
We need this to bump prometheus-operator in CMO, currently, it fails as we have a mismatch of versions.
cc @s-urbaniak
> Bump prometheus-operator to 0.32

- OWNERS
For some reason I thought I already was an owner/approver. Seems like this is still not the case :man_shrugging: 
/cc @squat
> Add metalmatze to the list of OWNERS

- jsonnet/telemeter/prometheus/kubernetes.libsonnet
- manifests/prometheus/list.yaml
- manifests/prometheus/serviceAccount.yaml
Currently, we've been using the same SA for the querier and the prometheus auth proxy. 
This PR adds another route to this oauth reference: the querier cache route. This route will be the frontend for the querier and will cache client requests going into the querier.
> Add Oauth reference to prometheus telemeter SA

- pkg/authorize/handler.go
- pkg/authorize/tollbooth/tollbooth.go
This commit fixes the authorization handler used by the receive endpoint
to expect a token encoded in base64.
cc @metalmatze @brancz
> pkg/authorize: decode token from base64

- cmd/telemeter-client/main.go
- cmd/telemeter-server/main.go
Make the limits on both the client and server configurable so that the
limits can be adjusted without needed to build new binaries.
cc @kakkoyun @brancz @metalmatze
> cmd: add limit-bytes flag

- Makefile
- jsonnet/jsonnetfile.json
- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/client/kubernetes.libsonnet
- manifests/benchmark/clusterRoleBindingPrometheusOperator.yaml
- manifests/benchmark/deploymentPrometheusOperator.yaml
- manifests/benchmark/serviceAccountPrometheusOperator.yaml
- manifests/client/deployment.yaml
The configmap reload for telemeter client was pointing to an unused port,
meaning that it would never reload anything.
Backport to the 4.1 release of https://github.com/openshift/telemeter/pull/229/files
cc @s-urbaniak @squat
> Bug 1746711: fix client reload port

- Makefile
- test/e2e/forward_test.go
The e2e tests were never being run as part of the CI workflow. Also,
because the e2e test files were excluded from the list of packages, they
were not statically checked.
All metrics received by the v1 ingester and forwarded will have their
timestamps overwritten by the validator, so it doesn't make sense to
ensure that the timestamp is unchanged.
cc @kakkoyun @metalmatze
> test/e2e: fix forward test

- Makefile
- cmd/telemeter-server/main.go
- go.mod
- go.sum
- jsonnet/server.jsonnet
- jsonnet/telemeter/server.libsonnet
- jsonnet/telemeter/server/kubernetes.libsonnet
- pkg/authorize/handler.go
- pkg/authorize/tollbooth/tollbooth.go
- pkg/cache/cache.go
- pkg/cache/memcached/memcached.go
- test/integration-v2.sh
- test/integration.sh
- vendor/github.com/bradfitz/gomemcache/LICENSE
- vendor/github.com/bradfitz/gomemcache/memcache/memcache.go
- vendor/github.com/bradfitz/gomemcache/memcache/selector.go
- vendor/modules.txt
This commit adds new functionality to Telemeter server to enable it to
cache the responses to authentication requests made while handling
remote-write requests. The only currently implemented backend is
Memcached, because it is so simple, but any shared k-v would serve our
purposes.
cc @bwplotka @aditya-konarde @brancz @kakkoyun
>  cmd/telemeter-server,pkg/cache: cache auth resps

- pkg/cluster/memberlist.go
Currently, if telemeter-server is run without the `-v` flag, it will
bail with the following error:
```
level=info caller=main.go:156 ts=2019-12-11T14:09:52.043501508Z msg="Telemeter server initialized."
level=error caller=main.go:159 ts=2019-12-11T14:09:52.221533957Z err="unable to configure cluster: Cannot specify both LogOutput and Logger. Please choose a single log configuration setting."
```
This commit fixes the configuration of the logger for memberlist so that
it telemeter-server can be run without `-v`.
XREF: https://github.com/openshift/telemeter/pull/237
cc @kakkoyun @metalmatze @brancz @bwplotka 
> pkg/cluster: fix running telemeter without verbose

- jsonnet/telemeter/server.libsonnet
- jsonnet/telemeter/server/kubernetes.libsonnet
This commit corrects the offset of the Memcached replica names.
StatefulSet replica names begin with `0` not `1`.
cc @bwplotka @metalmatze @brancz
> jsonnet/telemeter: fix memcached replica offset

- cmd/telemeter-server/main.go
- pkg/cache/memcached/memcached.go
We need to be able to update the DNS for the Memcached DNS servers
to keep up with changes in the IPs of the servers. This implements a
simple time-based DNS update.
cc @metalmatze @brancz @kakkoyun
> pkg/cache: update memcached dns on interval

- jsonnet/telemeter/lib/list.libsonnet
- jsonnet/telemeter/server.libsonnet
- jsonnet/telemeter/server/kubernetes.libsonnet
This commit introduces the memcached-exporter so that we can monitor
memcached. It also introduces some controls on the memcached process,
modeled after the grafana memcached jsonnet library:
https://github.com/grafana/jsonnet-libs/tree/master/memcached.
cc @metalmatze @brancz @kakkoyun
> jsonnet/telemeter: monitor memcached

- pkg/authorize/handler.go
Just a small one that I noticed as I was trying to investigate the failing requests on staging.
We previously attempted to double-read here which will always result in an empty body.
@squat @metalmatze @kakkoyun @bwplotka
> pkg/authorize: Print body on unexpected authz request result

- jsonnet/telemeter/lib/list.libsonnet
Currently if a container has no command, then the container will be
removed. This fixes the function.
cc @bwplotka @kakkoyun 
> jsonnet/telemeter: fix setMemcached func

- pkg/store/forward/forward.go
Until now we had transient errors for failures in forwarding the time series from our v1 /upload endpoint to the internal v2 Thanos receive hashring.
As we're defaulting to v2 soon and then want consistency, we should start enforcing those writes to fail. We didn't have any alerts firing on too many forwarding errors anyway.
/cc @brancz @bwplotka @kakkoyun @squat
> Enforce forwarding from v1 /upload to v2 receive hashring

- Makefile
This PR fixes integration tests that are broken after a dependency update.
The pipeline now uses a fixed version of the tool.
> test: Use specific version of UP to fix broken integration tests

- Makefile
- go.mod
- go.sum
- test/integration-v2.sh
- test/integration.sh
- vendor/github.com/observatorium/up/.drone.yml
- vendor/github.com/observatorium/up/.errcheck_excludes
- vendor/github.com/observatorium/up/.gitignore
- vendor/github.com/observatorium/up/.golangci.yml
- vendor/github.com/observatorium/up/Makefile
- vendor/github.com/observatorium/up/README.md
- vendor/github.com/observatorium/up/go.mod
- vendor/github.com/observatorium/up/main.go
- vendor/github.com/prometheus/client_golang/api/client.go
- vendor/modules.txt
This commit updates the telemter v2 integration test to use UP for the
querying functionality, rather than using a bash loop.
cc @kakkoyun
> test: use UP for querying in integration test

- jsonnet/telemeter/server/kubernetes.libsonnet
This PR intends to take the authorization URL out of the template and into the telemeter-server Secret.
required for https://github.com/observatorium/configuration/pull/149
ultimately the purpose of this PR is to allow deploying ConfigMaps via upstream!
> Consume authorize_url from Secret

- jsonnet/telemeter/rules.libsonnet
We have defined the OpenShift SLI based on whether the cluster
version operator is reporting a failure or not over a period of
time. To better support queries that attempt to aggregate availability
over classes of cluster, create a recording rule that is 1 when
a cluster is available and 0 when the cluster is reporting unhealthy.
If the cluster is not reporting any metrics it would have no data
at that point in time. Include the current version of the cluster
since it is implicit at the time of the recording rule.
This can be used in more complex aggregates by joining on cluster
id.
> jsonnet/telemeter: Add recording rule for cluster availability

- pkg/receive/handler.go
status code, i.e. it does not overwrite the status code returned by the
downstream handler.
cc @metalmatze @brancz @kakkoyun @bwplotka
> pkg/receive: return correct status code

- jsonnet/telemeter/rules.libsonnet
There are a number of key dimensions joined against the subscription data
that almost all queries base on.
1. Is it subscribed 
2. Is it internal 
3. Is it openshift dedicated 
4. Is it in a range of versions
5. AND is it currently running (subscription_labels does not check that)
This recording rule collapses those into a single metric with cardinality
O(clusters) that should dramatically reduce the cost of queries.
Combined with the previous rule (available) the extremely common query
"which subscribed clusters are unhealthy" becomes
```
id_version:cluster_available == 0 + on(_id) max by (_id) (id_version_ebs_account_internal:cluster_subscribed == 1)
```
This also reduces the data that must be searched for almost all other joins
and some dashboards.
Question: how expensive is this …
> jsonnet/telemeter: Record a "subscribed cluster" metric

- build_deploy.sh
- dockerfiles/Dockerfile.build
- dockerfiles/Dockerfile.deploy
- dockerfiles/README.txt
This commit eliminates the dockerfiles directory at the root of the
repository and updates the build_deploy.sh script used by App-SRE
tooling to directly use the main Dockerfile.
cc @jfchevrette @jmelis @brancz
> dockerfiles: simplify app-sre build tooling

- cmd/telemeter-server/main.go
- pkg/receive/handler.go
- pkg/store/forward/forward.go
Today, we only track the number of errors encountered when forwarding requests from the v1 upload endpoint to thanos. We don't track the total amount of requests made from the v1 upload endpoint handler. We also don't track any requests made when forwarding requests from the v2 endpoint to thanos.
This PR adds these metrics to give us better visibility during another incident.
cc @metalmatze @brancz @bwplotka @kakkoyun
> Fix remote write metrics

- Makefile
- jsonnet/benchmark.jsonnet
- jsonnet/telemeter/benchmark.libsonnet
- manifests/benchmark/statefulSetTelemeterServer.yaml
The metrics list was accidentally removed from the benchmark manifests in
a previous commit. This caused all benchmark tests to run without
telemeter-server accepting any metrics from the client, causing zero
load on the backend.
This commit reintroduces the metrics into the benchmarking manifests
using a jsonnet top-level-function.
cc @brancz @metalmatze
> jsonnet/benchmark: ensure benchmark has metrics

- jsonnet/jsonnetfile.lock.json
- jsonnet/telemeter/jsonnetfile.json
This commit removes the prometheus operator jsonnet dependency, as this
is no longer needed.
cc @brancz
> jsonnet: remove prometheus operator

- jsonnet/telemeter/client/kubernetes.libsonnet
- manifests/client/deployment.yaml
This sets CPU requests to what I measured during an e2e run.
At the same time it unsets limits as this was recommended for OpenShift workloads.
> Bug 1812719: jsonnet/telemeter: set cpu requests, unset limits

- cmd/telemeter-server/main.go
- pkg/receive/handler.go
- test/e2e/forward_test.go
- test/e2e/receive_test.go
Let's decode the receive requests and check if the partitionKey (for us mostly `_id`) is available in the request and otherwise reject the request.
> Receive requests are required to have partitionKey label

- cmd/telemeter-server/main.go
This helps making individual dependencies more clear and should show
better how to refactor going forward.
/cc @squat
> Move all routes and handlers into scoped blocks

- Makefile
- jsonnet/telemeter/client/kubernetes.libsonnet
- manifests/client/deployment.yaml
/cc @openshift/openshift-team-monitoring
> Bug 1813221: jsonnet/telemeter: set cpu requests, unset limits

- jsonnet/telemeter/rules.libsonnet
By default these rules get evaluated every 30s and right now we need ~40s  to evaluate them.
Every 60s should be plenty in normal circumstances.
/cc @squat @bwplotka
> Evaluate Telemeter rules only every minute

- pkg/server/forward.go
- pkg/server/ratelimited.go
- pkg/server/validator.go
For every middleware or handler we create a new logger and get the request ID from the request.Context. However, adding a new key-value-pair to the logger per request, we need a new request logger instance. That why we now have `rlogger` to create the request logger.
/cc @brancz @kakkoyun @squat
> Create a request logger per middleware / handler

- pkg/receive/handler.go
- pkg/server/forward.go
@metalmatze @squat @kakkoyun @bwplotka @krasi-georgiev
> telemeter-server: Always set OpenShift telemetry tenant ID

- cmd/telemeter-server/main.go
- pkg/receive/handler.go
- pkg/server/forward.go
- test/e2e/forward_test.go
- test/e2e/receive_test.go
Follow up from #332 
@squat @metalmatze @kakkoyun @krasi-georgiev @bwplotka
> telemeter-server: Make downstream tenant ID configurable

- jsonnet/telemeter/client/kubernetes.libsonnet
- jsonnet/telemeter/server/kubernetes.libsonnet
- manifests/client/deployment.yaml
This upgrades both the client and server to use the apps/v1 API as in 1.16 the apps/v1beta2 API is removed.
@openshift/openshift-team-monitoring @metalmatze @squat
> jsonnet: Upgrade apps API versions used to apps/v1

- cmd/telemeter-server/main.go
- pkg/server/forward.go
- test/e2e/forward_test.go
Somewhere in here is probably a leak and I can only really reproduce on
our production system, so here we go.
If these are fine, then we can re-enable one by one until we fine out
which one is responsible.
/cc @squat
> Don't wrap forwardClient's transport with additional roundtrippers

- Dockerfile
- Fixing maintainer label to end with @redhat.com as this is expected
- Overriding summary label as it is inherited from base image and results with an incorrect value
- ~explicit golang 1.14 usage~
- ~explicit usage of openshift base image (as it is used in OSBS)~
/cc @openshift/openshift-team-monitoring
> Bug 1867510: fix CVP issues due to incorrect labels set

- pkg/authorize/handler.go
We really want to propagate the status codes we got from Tollbooth, so we don't alert on too many 5xx if we get 4xx from Tollbooth...
> Bug 1874112: Do not overwrite 3xx and 4xx from Tollbooth to 500

- jsonnet/telemeter/rules.libsonnet
In order to make estimation of cluster distribution easier, synthesize the following recording rules that remove the need for complex joins in other queries by _id:
* `version` - the current version of the cluster or empty string if the cluster did not report the metric
* `host_type` - an enumeration representing the most common types of hardware within a cluster by node count - metal, known virt types, cloud types (which may cover hardware)
* `provider` - an enumeration representing the cloud provider type when known
* `install_type` - an enumeration representing how the cluster was installed
Each of these attempt to classify all clusters reporting to telemetry:
* Clusters older than the metrics that started reporting these values
* Clusters with topologies that are missing subsets of …
> Bug 1877816: Provide synthetic recording rules for common cluster id -> key dimensional joins

- jsonnet/telemeter/rules.libsonnet
Now that real data is being generated, fix the following problems
in the rules:
1. typo use of `provider` as the query instead of `id_provider`
2. fix multiple series generated for the same _id for id_version and
id_install_type
3. Guard the recording rule for duplicate series in the future
> Bug 1879009: jsonnet/telemeter: Fix cluster_subscribed recording rule

- jsonnet/telemeter/rules.libsonnet
Joining on `primary_host_type` was incorrect and did not add the label.
> Bug 1879965: jsonnet/telemeter: Use `host_type` in recording rule join

- jsonnet/telemeter/rules.libsonnet
All known cloudpaks install at least one of the 'ibm-common-service'
operator or the 'ibm-licensing-operator'. To better track the known
cloudpaks report a metric that encodes the cloudpak_type of a cluster.
For now the only value reported is `unknown` to leave room to detect
type in the future.
A subsequent change will add this to the summary recording rule.
> jsonnet/telemeter: Record which cloudpak a cluster appears to be

- jsonnet/telemeter/rules.libsonnet
Combine the class and email_domain fields on subscription labels into
a smaller subset query. Add internal as it is used today for legacy
behavior, but leverage class to better discriminate between different
types of accounts (Internal, Customer, Partner, or Evaluation). The
resulting account_type should be used for classification of the
customer type.
Will be used for other joins and significantly reduces cardinality
of queries by avoiding subscription_labels
> jsonnet/telemeter: Add a rule for normalizing ebs_account data

- Makefile
- jsonnet/telemeter/rules.libsonnet
- tools/tools.go
This commit adds a Makefile target to format all jsonnet code. It also
removes "shellcheck" from the "format" target, as it is a linting tool,
not a formatter.
Includes fix from #364
> Makefile: enable jsonnetfmt check

- jsonnet/telemeter/client/kubernetes.libsonnet
- manifests/client/deployment.yaml
As reported in https://bugzilla.redhat.com/show_bug.cgi?id=1905330 we must set the memory requests of the `telemeter-client` and `reload` containers before https://github.com/openshift/origin/pull/25747 lands.
/cc @openshift/openshift-team-monitoring
> Bug 1905330: jsonnet: add memory requests to client containers

- jsonnet/telemeter/rules.libsonnet
This PR replaces #381
Invoker value `assisted-installer-operator` helps us differentiate
between clusters installed by the SaaS offering of the assisted installer,
and clusters installed by assisted installer operator. For marketing
reasons, the value is mapped to `infrastructure-operator` install type.
> Add 'infrastructure-operator' value to 'install_type' label

- OWNERS
When things started out and we had just a few services to run, it made sense that we attempt to be approvers on each of the repositories.
As we manage dozens of services with hundreds of repos, this approach no longer scales and we had decided to not proceed with it. Here is the MR to our onboarding docs which removes this section: https://gitlab.cee.redhat.com/service/app-interface/-/commit/5dd6d564a822ee05eedb7622ea672ea6cc37ebf7
As such, I am submitting this PR to remove all of AppSRE from being approvers.
> remove AppSRE from owners

- jsonnet/telemeter/client/kubernetes.libsonnet
- manifests/client/deployment.yaml
To fix the warning
```
spec.template.spec.nodeSelector[beta.kubernetes.io/os]: deprecated since v1.14; use "kubernetes.io/os" instead
```
> Bug 1995614: Update nodeSelector

- jsonnet/telemeter/client.libsonnet
- jsonnet/telemeter/client/kubernetes.libsonnet
- manifests/client/deployment.yaml
- manifests/client/service.yaml
To telemeter-client, add `app.kubernetes.io/part-of` label to [refer  at telemeter-client deployed by CMO](https://github.com/openshift/cluster-monitoring-operator/pull/1205/#discussion_r660375686) .
> add app.kubernetes.io/part-of label to telemeter client

- OWNERS
Signed-off-by: Matej Gera <matejgera@gmail.com>
Updates the OWNERS file to include Jéssica Lins (@jessicalins) from RHOBS team, who is currently missing.
> OWNERS: Add Jéssica Lins

- jsonnet/telemeter/client/kubernetes.libsonnet
- manifests/client/servingCertsCABundle.yaml
This commit fixes the invalid configmap definition created by https://github.com/openshift/telemeter/pull/398.
Also this moves to "service.beta.openshift.io/inject-cabundle" annotation.
Without this fix, following errors were seen while deploying CMO,
```
I1102 22:23:40.699907   50143 operator.go:603] ClusterOperator reconciliation failed (attempt 2), retrying.
E1102 22:23:40.699919   50143 operator.go:490] Syncing "openshift-monitoring/cluster-monitoring-config" failed
E1102 22:23:40.699928   50143 operator.go:491] sync "openshift-monitoring/cluster-monitoring-config" failed: cluster monitoring update failed (reason: UpdatingTelemeterClientFailed)
```
Blocks https://github.com/openshift/cluster-monitoring-operator/pull/1455
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>
> client: Fix invalid serving-certs-ca configmap

- jsonnet/telemeter/client/kubernetes.libsonnet
- manifests/client/prometheusRule.yaml
Issue https://bugzilla.redhat.com/show_bug.cgi?id=2057832
Problem: Current recording rule expression isn't completely
accurate since it may count more series than what is effectively sent to telemeter.
Furthermore the PrometheusRule should be hosted by the telemeter project
Solution: Move the telemetry rule to the telemetry repo and for the
expression instead metrics from telemeter-client which capture
exactly the number of samples being sent.
> Adds PrometheusRule telemetry that was previously hosted in cluster-monitoring-operator

- jsonnet/telemeter/rules.libsonnet
Signed-off-by: Matej Gera <matejgera@gmail.com>
We are currently seeing a numerous alerts about long evaluation duration, due to the fact that some of the rules are now taking much longer to evaluate (presumably due to larger data set, some rules take now 30-60 seconds to evaluate, thus always exceeding the evaluation interval).
Based on the discussions (https://coreos.slack.com/archives/G79AW9Q7R/p1658752053857949), there actually does not seem to be a need to evaluate the rules every minute. Hence, I'm bumping the interval to alleviate the issue with evaluation duration.
> Bump Telemeter rules evaluation interval to 3m

- jsonnet/telemeter/rules.libsonnet
This PR bumps the rules evaluation interval from 3m to 4m as we are still seeing flappy alerts due to long rule evaluation as per https://issues.redhat.com/browse/MON-2697. This is a follow-up to #417.
> Bump Telemeter rules evaluation interval to 4m

- pkg/receive/handler.go
This PR allows telemeter receive path to propagate any upstream errors.
> pkg/receive/handler: Propagate upstream error message

- cmd/telemeter-server/main.go
- pkg/receive/handler.go
- test/e2e/receive_test.go
This PR makes sure that /metrics/v1/receive handler uses the OIDC forwardClient to send requests to Observatorium API instead.
> pkg/receive/handler: Use OIDC client

- cmd/telemeter-server/main.go
- pkg/receive/handler.go
- test/e2e/receive_test.go
This PR adds a `TransformWriteRequest` middlerware to /metrics/v1/receive, to allow applying whitelist rules and elide labels to remote write requests.
> pkg/receive/handler: Add middleware to respect whitelist + elide

- cmd/telemeter-server/main_e2e_test.go
- pkg/server/forward.go
- pkg/server/forward_test.go
Signed-off-by: Matej Gera <matejgera@gmail.com>
Since Thanos Receiver from version `0.28.0` will require the labels to be valid (ordered, no duplicates and no empty labels), we need to ensure whatever we receive from client will contain valid labels.
Added tests to the conversion method to test that sanitizing labels works.
> Forward: Add logic to sanitize labels

- jsonnet/telemeter/rules.libsonnet
These are intended to help simplify PromQL used by subscription watch,
as well as make it more visible to others.
Additionally, the encapsulation allows us to tweak the definition of
CPU-hours or instance-hours if better underlying metrics are made
available.
Note this is untested, but I'm happy to assist with testing, but I lack context/fixtures.
> Add rules for cluster CPU-hours and Instance-hours

- cmd/telemeter-server/main.go
- pkg/receive/handler.go
- test/e2e/receive_test.go
This PR adds a couple of new counters to accurately measure any request failures due to body size limit and request label validations.
This also refactors handler to ensure we decode and encode remote-write protobufs only once for transforming/validating remote write requests.
> Add metrics for telemeter receive path

- jsonnet/telemeter/rules.libsonnet
When no infrastructure provider or no install type are reported by a cluster, the respective provider or install type is labeled as 'hypershift-unknown'. This causes confusion implying that these clusters have something to do with hypershift hosted clusters. This applies a value of 'unknown' instead.
> Replace 'hypershift-unknown' with 'unknown'

- jsonnet/telemeter/rules.libsonnet
Clusters installed with an invoker value of 'hypershift' should get an install type of 'hypershift'. This will help us identify which clusters are installed by the hypershift operator vs standalone.
> Add 'hypershift' value to 'install_type' label

- cmd/telemeter-server/main.go
The logging level was never respected since the flag value only become available within `Run`.
This change sets a levelled logger based on the value of the flag as expected!
Before and after screenshots of the debugger below.
> server: Ensure logging level is flag is respected

- jsonnet/telemeter/rules.libsonnet
Clusters installed with an invoker value of '[agent-installer](https://github.com/openshift/installer/pull/6418)' should get an install_type of 'agent-installer'.
> OCPBUGS-6962: Add 'agent-installer' value to 'install_type' label

- jsonnet/telemeter/rules.libsonnet
Clusters installed with an invoker value of 'agent-installer' should get an install_type of 'agent-installer'.
> OCPBUGS-7702: Add 'agent-installer' value to 'install_type' label

- cmd/telemeter-server/main.go
- pkg/receive/handler.go
- test/e2e/receive_test.go
This PR ensures that receive methods don't need a separate logger and use the one passed into `handler` itself. Mergeable after #449 goes in.
> Use receive handler logger

- README.md
- test/integration.sh
Test documentation is old and not accurate. 
Command ./test/integration.sh has path of binaries broken, better use "make test-integration"
No args are passed to integration.sh
> Fix integration test documentation

- pkg/http/roundtripper.go
Improve debug roundtripper logs splitting in different lines
> Improve debug roundtripper logs

- cmd/telemeter-client/main.go
- jsonnet/telemeter/client/kubernetes.libsonnet
- manifests/client/deployment.yaml
- manifests/client/service.yaml
- pkg/forwarder/forwarder.go
- pkg/http/roundtripper.go
Add TLS auth to forwarder in order to authorize telemeter against rbac Prometheus proxy. Change FROM to 9092 proxy port.
This PR works together with this CMO: https://github.com/openshift/cluster-monitoring-operator/pull/1904
> MON-3230: Add TLS auth to telemeter-client

- jsonnet/telemeter/server/rhelemeter-kubernetes.libsonnet
Add secrets for external mtls connection with rhel clients.
> [rhelemeter]: add secret for external mtls connection

- jsonnet/telemeter/rules.libsonnet
This is to fix OCPBUGS-16397: Nutanix OCP cluster telemetry data "host_type" shows "virt-unknown".
Similar to other cloud providers, Nutanix also need to identify its "host_type" in the telemetry data. Refer to  https://github.com/openshift/telemeter/pull/356.
> OCPBUGS-16397: Nutanix OCP cluster telemetry data "host_type" shows "virt-unknown"

- cmd/telemeter-server/main.go
- pkg/authorize/client.go
- pkg/authorize/handler.go
- pkg/authorize/jwt/client_authorizer.go
- pkg/authorize/jwt/handler.go
- pkg/authorize/tollbooth/tollbooth.go
- pkg/cache/cache.go
- pkg/receive/handler.go
- pkg/server/ratelimited.go
- pkg/server/requestlog.go
- pkg/server/validator.go
Improve logging for incident resolution by:
- Adding a request logger
- Adding request id in all logs (was not consistently done)
- Adding some missing logs
To be noted: As a result of some simplifications, following error messages are now returned to the client from `pkg/authorize/jwt/client_authorizer.go`:
```
func (j *clientAuthorizer) AuthorizeClient(tokenData string) (*authorize.Client, error) {
if !j.hasCorrectIssuer(tokenData) {
return nil, false, nil
}
tok, err := jwt.ParseSigned(tokenData)
if err != nil {
return nil, false, nil
}
```
I don't see it as an issue. In fact, quite the opposite. Let me know if you disagree.
> RHOBS-870: Improve logging

- cmd/rhelemeter-server/README.md
- cmd/rhelemeter-server/main.go
- cmd/rhelemeter-server/main_e2e_test.go
- cmd/telemeter-server/main.go
- pkg/authorize/ssl/ssl.go
- pkg/authorize/ssl/ssl_test.go
- pkg/receive/handler.go
- test/e2e/receive_test.go
The rhelemeter server exposes remote write API and this change allows us to do some further validation on the incoming requests. 
Right now, the flow of traffic is a many-to-one relationship between hosts/VMs running RHEL OS and rhelemeter-server.
In some cases, an intermediate proxy will validate and terminate mTLS and in those cases, the proxy must forward on the client information, as well as a pre-shared key in a set of headers (configurable) like so
```
x-gateway-secret: ${PSK}  //Example PSK -> 46545757575
x-certauth-cn:  ${Certificate Subject}  //Example  Certificate Subject ->  "/O = 12345, /CN = 1234567-9b7c-48f6-8d5b-7654321
```
This change enables us to decode the Subjects CommonName and Organisation in middleware and set it on the context of the request to be dealt with …
> rhelemeter: Validation of incoming metrics

- jsonnet/telemeter/rules.libsonnet
Red Hat OpenShift Container Platform subscriptions are often measured against underlying cores. However, the metrics for cores are unreliable with some known edge cases. Namely, when virtualization is used, depending on a variety of factors, the hypervisor doesn't report the underlying cores, and instead reports a core per "cpu" where "cpu" is a schedulable executor (possibly backed by a single hyperthreaded executor). In order to address, we assume a ratio of 2-vCPU to 1 core, and divide the "cores" value by 2 to normalize when we detect that hyperthreading information was not reported, when we're on x86-64 CPU architecture.
At this time, x86-64 clusters with HT undetected or turned off are the ones affected.
The rule implementation itself divides the cluster into the following …
> MON-3669: Add rule for effective CPU cores for subscription usage purposes

- jsonnet/telemeter/rules.libsonnet
The blank newlines in the recording rules forces the [rhobs/config yaml parsing to insert escape chars `\n`](https://github.com/rhobs/configuration/pull/675/files#diff-08c043e75a0ae296db7120a1952f4272a89f4897e3af5c8433af63a6bf814423R2150) into the expression, rendering it invalid promql. 
This change allows us to render the yaml properly on our side.
> MON-3669: Removing newlines from the jsonnet configuration for the recording rules.libsonnet

- jsonnet/telemeter/rules.libsonnet
to catch nutanix_ahv which is what the cluster:virt_platform_nodes:sum expression assumes
> OCPBUGS-16397: update nutanix filter

- jsonnet/telemeter/rules.libsonnet
Related: https://issues.redhat.com/browse/MON-3669.
This addresses a bug where 0 was the effective value due to label mismatches in `cluster:cpu_capacity_cores:_id`.
When we added a recording rule named `cluster:cpu_capacity_cores:_id`, the recorded time series includes a tenant_id label and so it's not equivalent to the expression it replaced.
Adding `tenant_id` to the `sum by` expression makes it properly match the `cluster:cpu_cpacity_cores:_id` series.
> MON-3669: fix join issue in cluster:capacity_effective_cpu_cores

- Makefile
- README.md
- jsonnet/telemeter/rules.libsonnet
- test/rulestests.yaml
Simplify by dividing all x86_64 cpu counts by 2.
Note that this takes advantage of the way that the SKUs are structured, where the capacity is written as multiples of "2 cores or 4vCPUs".
One difference in how this simplification works is that with nodes reporting more than 2 threads-per-core will be counted by CPUs, rather than by cores.
When exactly 2 threads-per-core are reported, there is no functional difference, as node_role_os_version_machine:cpu_capacity_cores:sum already divides CPUs by 2.
This adds testing similar to what's in cluster-monitoring-operator, covering only the `cluster:capacity_effective_cpu_cores` rule.
I had to update the prometheus version, as promtool was too old and incorrectly flagging existing rules.
I added a note about rule tests to the README.
I did not …
> RHOBS-995: Simplify cluster:capacity_effective_cpu_cores, add tests

- .gitignore
- Makefile
- tools/go.mod
- tools/tools.go
The documentation about metrics being forwarded via Telemetry lives in the cluster-monitoring-operator repository.
> MON-3715: remove obsolete targets from Makefile

- Makefile
Change pinned memcached binary downloaded in makefile. Related to this PR https://github.com/openshift/release/pull/50465 that install memcached as a dnf dependency.
memcached binary was download from archlinux archive and pinned to an old image that create some issues in integration test.
Update otelcol to last version
> MON-3737: Update binaries to new version

- .gitignore
- jsonnet/telemeter/rules.libsonnet
- test/rulestests.yaml
Those recording rules will be used for the (new) billing of ROSA
Closes [OSD-25491](https://issues.redhat.com//browse/OSD-25491) and [OSD-25492](https://issues.redhat.com//browse/OSD-25492)
> OSD-25491,OSD-25492:New recording rules averaging CPU consumption for ROSA HCP & ROSA classic clusters

- jsonnet/telemeter/rules.libsonnet
Follow-up of the discussion on #544. This PR creates a recorded metric which we can use in the follow-up recording rules instead of hardcoding `count_over_time(vector(1)[1h:5m])` everywhere.
> NO-JIRA: add `steps:count1h` recording rule

- jsonnet/telemeter/rules.libsonnet
- test/rulestests.yaml
A recording rule needs to aggregate worker nodes under the hub cluster so swatch can associate the metric with the hub's billing account information.
Create a new recording rule that uses the existing one, and adds the "sum" logic on top of it.
> SWATCH-3413: Add acm_capacity_effective_cpu_cores:sum recording rule

- pkg/metricfamily/elide.go
We came across this case when dealing with a metric sent by telemeter-client that was not in the allowlist.
The whitelister sets the metric as nil, and as elide is the transformer right after whitelister, it comes across the nil metric and panics as a result.
> OCPBUGS-50837: Check nil metric in elide label
